from utils import system, dependencies
from utils.dependencies import get_tbb_lib, add_optional_libs

from utils.build_tools import find_files_recursive, link_usd_libraries
import os
import os.path

Import('env')
local_env = env.Clone()

src_base_dir  = os.path.join(local_env['ROOT_DIR'], 'tools/turntable')
source_files = find_files_recursive(src_base_dir, ['.c', '.cpp'])

# Reset inherited include paths: this tool only needs USD, not Arnold.
includePaths = [
    '.',
    local_env['USD_INCLUDE'],
]
for opt in ['BOOST_INCLUDE', 'TBB_INCLUDE']:
    val = local_env.get(opt)
    if val:
        includePaths.append(val)
local_env['CPPPATH'] = includePaths

usd_deps = None
# Shared monolithic
if local_env['USD_BUILD_MODE'] == 'monolithic':
    usd_deps = [
        local_env['USD_MONOLITHIC_LIBRARY'],
        get_tbb_lib(local_env),
    ]
    if system.is_linux:
        usd_deps = usd_deps + ['dl', 'pthread']
    usd_deps = add_optional_libs(local_env, usd_deps)

# Static monolithic
elif local_env['USD_BUILD_MODE'] == 'static':
    if system.is_windows:
        usd_deps = [
            '-WHOLEARCHIVE:libusd_m',
            'Ws2_32',
            'Dbghelp',
            'Shlwapi',
            'advapi32'
        ]
        if not local_env['TBB_STATIC']:
            usd_deps += [get_tbb_lib(local_env)]

        extra_static_libs = local_env["EXTRA_STATIC_LIBS"]
        if extra_static_libs:
            extra_static_libs_list = extra_static_libs.split(';')
            for extra_lib in extra_static_libs_list:
                usd_deps.append('-WHOLEARCHIVE:{}'.format(extra_lib))
    else:
        whole_archives = ['%s/libusd_m.a' % local_env.subst(local_env['USD_LIB'])]
        if local_env['TBB_STATIC']:
            whole_archives.append('%s/libtbb.a' % local_env.subst(local_env['TBB_LIB']))
        else:
            usd_deps = [get_tbb_lib(local_env)]
        whole_archives.extend(local_env["EXTRA_STATIC_LIBS"].split(';'))
        if system.is_linux:
            local_env.Append(LINKFLAGS=['-Wl,--whole-archive,%s,--no-whole-archive' % ','.join(whole_archives)])
            local_env.Append(LIBS = ['dl', 'pthread'])
        elif system.is_darwin:
            for whole_archive in whole_archives:
                local_env.Append(LINKFLAGS=['-Wl,-force_load,{}'.format(whole_archive)])
            extra_frameworks = local_env['EXTRA_FRAMEWORKS']
            if extra_frameworks:
                extra_frameworks = extra_frameworks.split(';')
                local_env.Append(FRAMEWORKS = extra_frameworks)

# Shared libs
else:
    usd_libs = [
        'ar',
        'arch',
        'plug',
        'tf',
        'vt',
        'sdf',
        'usd',
        'usdGeom',
        'usdLux',
        'usdRender',
        'usdShade',
    ]
    usd_libs, _ = link_usd_libraries(local_env, usd_libs)
    usd_deps = [get_tbb_lib(local_env)]
    if system.is_linux:
        usd_deps = usd_deps + ['dl']
    usd_deps = usd_deps + usd_libs
    add_optional_libs(local_env, usd_deps)

if usd_deps:
    local_env.Append(LIBS = usd_deps)

TURNTABLE = local_env.Program('turntable', source_files)

Return('TURNTABLE')
