# Copyright 2019 Autodesk, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import os
from utils import system, build_tools, dependencies

Import('env')
local_env = env.Clone()

src_dir = os.path.join(env['ROOT_DIR'], 'ndr')
source_files = [
    'discovery.cpp',
    'parser.cpp',
    'utils.cpp',
]

if system.os != 'windows':
    local_env.Append(CXXFLAGS = Split('-fPIC'))

local_env.Append(CPPDEFINES=['NDRARNOLD_EXPORTS'])
local_env.Append(CPPDEFINES=['ARNOLDUSD_EXPORTS'])
local_env.Append(CPPPATH = [os.path.join(env['BUILD_ROOT_DIR'], 'ndr')])
local_env.Append(LIBS = ['ai'])

source_files, usd_deps = dependencies.ndr_plugin(local_env, source_files)
local_env.Append(LIBS = usd_deps)

# Otherwise we are getting a build error.
if not system.IS_WINDOWS:
    local_env['STATIC_AND_SHARED_OBJECTS_ARE_THE_SAME'] = 1
source_files.append([local_env.Object(target = os.path.join(local_env['BUILD_ROOT_DIR'], 'ndr', 'common', '%s.o' % os.path.basename(src)), source = src) for src in local_env['COMMON_SRC']])
NDRPLUGIN = local_env.SharedLibrary('ndrArnold', source_files)
Return('NDRPLUGIN')
