# Copyright 2022 Autodesk, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import os
from utils import system, dependencies, configure

Import('env')
local_env = env.Clone()

source_files = [
    'lightLinkingSIP.cpp',
    'implicitSurfaceSIP.cpp',
    'dependenciesSIP.cpp',
    'dependencyForwardingSIP.cpp',
    'extComputationPrimvarPruningSIP.cpp',
	'fixInvalidationSIP.cpp',
	'fixMaterialPruningSIP.cpp',
    'fixPropagatedPrototypesVisibilitySIP.cpp',
	'propagateDirtyPrimsSIP.cpp',
    'nurbsApproximatingSIP.cpp',
    'meshLightResolvingSIP.cpp',
    'renderPassSIP.cpp',
]

if not system.is_windows:
    local_env.Append(CXXFLAGS = Split('-fPIC'))
    local_env.Append(CXXFLAGS = Split('-Wno-deprecated -Wno-deprecated-declarations -Wno-deprecated-builtins'))

local_env.Append(CPPDEFINES=['HDSCENEINDEX_EXPORTS'])
local_env.Append(CPPPATH = [os.path.join(env['ROOT_DIR'], env['BUILD_BASE_DIR'], 'plugins', 'scene_index')])
common_lib_path = os.path.abspath(os.path.join(local_env['BUILD_BASE_DIR'], 'libs', 'common'))
local_env.Append(LIBPATH = [common_lib_path])
local_env.Append(LIBS = ['ai', 'common'])

if local_env['BUILD_SCENE_INDEX_PLUGIN']:
    local_env.Append(CPPDEFINES = ['ENABLE_SCENE_INDEX'])

# Otherwise we are getting a build error.
source_files, usd_deps = dependencies.scene_index_plugin(local_env, source_files)
local_env.Append(LIBS = usd_deps)

if env['USD_BUILD_MODE'] == 'static':
    SCENEINDEXPLUGIN = local_env.StaticLibrary('sceneIndexArnold', source_files)
else:
	SCENEINDEXPLUGIN = local_env.SharedLibrary('sceneIndexArnold', source_files, no_import_lib=True)
Return('SCENEINDEXPLUGIN')
