# vim: filetype=python
# Copyright 2019 Autodesk, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from utils import system, dependencies
from utils.build_tools import find_files_recursive, link_usd_libraries
import os
import os.path

Import('env')
local_env = env.Clone()

# import build env
src_base_dir  = os.path.join(local_env['ROOT_DIR'], 'cmd')
source_files = find_files_recursive(src_base_dir, ['.c', '.cpp'])
include_files = find_files_recursive(src_base_dir, ['.h'])
src_translator_dir  = os.path.join(local_env['ROOT_DIR'], 'translator', 'writer')

# Include paths
includePaths = [
    '.',
    src_translator_dir
]
local_env.Append(CPPPATH = includePaths)
local_env.Append(LIBS = ['ai'])

local_env.Append(LIBPATH = os.path.abspath(os.path.join(local_env['BUILD_BASE_DIR'], 'translator')))

source_files, usd_deps = dependencies.translator(local_env, source_files)
local_env.Append(LIBS = usd_deps)

ARNOLD_TO_USD = local_env.Program('arnold_to_usd', source_files)
Return('ARNOLD_TO_USD')
